#!/usr/bin/env python3

def problem5a():
    Array = []
    with open('file5.txt', mode = 'r') as f:
        lines = f.read().splitlines()
        for line in lines:
           Array = []
            if line.strip() == '':
if __name__ == "__main__":
    x = problem5a()
    print(x)
