#!/usr/bin/env python3


## In example i = [2-5, 3-4], ranges completely consist of each other iff,
## 2 < 3 and 5 > 4 , i.e i[0].split('-')[0] < i[1].split('-')[0]

with open('file4.txt', mode='r') as f:
    lines = f.read().splitlines()
    nline = [line.split(',') for line in lines]
    sum = 0
    for line in nline:
        print(line) #line is basically ['71-71', '2-25']
        # check if first index of first element (71) is less than or greater than first index of second element (2)
        if int(line[0].split('-')[0]) <= int(line[1].split('-')[0]) and int(line[0].split('-')[1]) >= int(line[1].split('-')[1]):
            print("Ranges completely covered by 1'st pair")
            sum += 1
        elif int(line[0].split('-')[0]) >= int(line[1].split('-')[0]) and int(line[0].split('-')[1]) <= int(line[1].split('-')[1]):
            print("Ranges completely covered by 2'nd pair")
            sum += 1
    print(sum)

