#!/usr/bin/env python3
import string

alphabets = list(string.ascii_letters) 
dict1 = {}
sum = 0
for i in range(len(alphabets)):
    dict1.update({alphabets[i]:i+1}) 



with open(file='file3.txt', mode='r') as f:
    for i in f.readlines():
        mid = len(i)//2
        right = i[mid:]
        left = i[:mid]
        print(i)
        print(left)
        print(right)
        for j in set(left):
            if j in right:
                print(j)
                sum += dict1.get(j)

print(sum)
print(dict1)
