#!/usr/bin/env python3

import string


alphabets = list(string.ascii_letters)
print(alphabets)
dict1 = {}
for i in range(0,len(alphabets)):
    dict1.update({alphabets[i]:i+1})

print(dict1)
tmpList = []
permList = []
sum = 0
with open('file3.txt', mode = 'r') as f:
    lines = [line.strip() for line in f]
    print(len(lines))
    for i in range(0,len(lines),3):
        tmpList.append(lines[i])
        tmpList.append(lines[i+1])
        tmpList.append(lines[i+2])
        permList.append(tmpList)
        tmpList = []
    for array in permList:
        print(array)
        letter = list(set(array[0]).intersection(array[1]).intersection(array[2]))
        print(letter)
        sum += dict1.get(letter[0])

print(sum)
